### ISSUE TITLE
Failed to commit new volume file while performing garbage collection on Windows

### ISSUE THREAD

**Issue by JavaNullPointer** [seaweedfs/seaweedfs#5066] opened 2023-12-04 07:21 UTC
**Describe the bug**
When the system runs for a while, the volume becomes unavailable, and when recreated, it shows that the. bat file is being occupied by other processes.
Causing historical files to be unreadable and writable, and being able to recover after restarting.
Tested other versions on Windows that also have the same issue, such as 3.51 and 3.59.

**System Setup**
Windows 11
version 30GB 3.58 windows amd64
Start with weed -logdir=D:\ims-data\seaweedfs\logs server -s3 -ip=0.0.0.0 -dir=D:\ims-data\seaweedfs\datanode -s3.port=8333 -s3.config=C:\ims-depends\seaweedfs\script\s3_auth_config.json -filer.port=8888 -master.port=9333 -master.volumeSizeLimitMB=30000 -volume.max=1400 -volume.port=9011
Upload a file and delete
Trigger the vacuum

**Expected behavior**
Vacuum completes with no errors.

**Screenshots**

**Additional context**
I1130 14:43:18.806449 volume_layout.go:383 Volume 4 becomes unwritable
I1130 14:43:18.806449 topology_vacuum.go:74 0 Start vacuuming 4 on 0.0.0.0:9011
I1130 14:43:18.822075 topology_vacuum.go:93 0 vacuum 4 on 0.0.0.0:9011 processed 292051360 bytes, loadAvg 0.00%
I1130 14:43:18.868939 needle_map_memory.go:111 loading idx from offset 0 for file: D:\ims-data\seaweedfs\datanode/test-bucket_4.cpx
I1130 14:43:18.931785 topology_vacuum.go:102 Complete vacuuming 4 on 0.0.0.0:9011
I1130 14:43:18.931785 topology_vacuum.go:128 Start Committing vacuum 4 on 0.0.0.0:9011
I1130 14:43:18.931785 volume_vacuum.go:106 Committing volume 4 vacuuming...
E1130 14:43:18.947110 volume_grpc_vacuum.go:89 failed commit volume 4: remove D:\ims-data\seaweedfs\datanode/test-bucket_4.dat: The process cannot access the file because it is being used by another process.
E1130 14:43:18.947110 topology_vacuum.go:144 Error when committing vacuum 4 on 0.0.0.0:9011: rpc error: code = Unknown desc = remove D:\ims-data\seaweedfs\datanode/test-bucket_4.dat: The process cannot access the file because it is being used by another process.

**Comment by chrislusf** [comment] 2023-12-04 18:56
this is a known issue and could not find out why the file handles are still considered open after they are all closed.

**Comment by JavaNullPointer** [comment] 2023-12-05 01:24
> this is a known issue and could not find out why the file handles are still considered open after they are all closed on Windows. Just do not use volume servers on windows.

This issue has resulted in the inability to use the latest version of seaweedfs on Windows, and only versions below 3.27 can be used. We hope the developer team can do their best to resolve this issue

**Comment by n9** [comment] 2023-12-05 07:45
I am not sure, whether there is a developer team. (Users usually fix bugs they need to be fixed.)

**Comment by hencoappel** [comment] 2024-04-02 12:51
This looks to be a duplicate of https://github.com/seaweedfs/seaweedfs/issues/4530

**Comment by kmlebedev** [comment] 2024-04-03 07:45
To check, you can take an already built binary from the branch master https://github.com/seaweedfs/seaweedfs/releases/tag/dev

**Comment by JavaNullPointer** [comment] 2024-04-03 08:21
> @JavaNullPointer my change has been merged, could you check if this fixes the issue for you?
After testing based on version wed-20240403-0319-windows-amd64, the issue has been fixed！

**Comment by chrislusf** [comment] 2024-04-03 15:13
@JavaNullPointer Thanks for confirming!
@hencoappel Thanks for the fix! This bug has bothered me for a long time! 👍

**Closed by chrislusf** 2024-04-03 15:13 UTC
