### ISSUE TITLE
Corrupted Files in Cluster

### ISSUE THREAD

**Issue by ProjectInitiative** [seaweedfs/seaweedfs#3183] opened 2022-06-15 03:51 UTC
**Describe the bug**
Files copied to FUSE filer mount are being corrupted.

**System Setup**
- OS version **Debian GNU/Linux 11 (bullseye)**
- output of `weed version` **version 8000GB 3.11 d4ef06cdcf320f8b8b17279586e0738894869eff linux amd64**

```toml
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = true

[leveldb3]
# similar to leveldb2.
# each bucket has its own meta store.
enabled = true
dir = "/opt/seaweedfs/REDACTED/filer/filerldb3"                    # directory to store level db files
```

**Expected behavior**
Files copied via FUSE mount should match md5sum like any other mount.

**Additional context**
fstab entry:

```ini
fuse /mnt/swfs/localshared fuse.weed filer='REDACTED:8889,REDACTED:8889,REDACTED:8889',filer.path=/,nofail 0 0
```

```bash
root:~# md5sum /var/lib/pve/local-btrfs/images/526/vm-526-disk-0/disk.raw 
fba3db35d8d631a8014bbf89dbb3e9ca  /var/lib/pve/local-btrfs/images/526/vm-526-disk-0/disk.raw
root:~# cp /var/lib/pve/local-btrfs/images/526/vm-526-disk-0/disk.raw /mnt/swfs/localshared/
root:~# md5sum /mnt/swfs/localshared/disk.raw 
f8555d7c8bc4e0081dde769255ddc815  /mnt/swfs/localshared/disk.raw
```

**Comment by ProjectInitiative** [comment] 2022-06-15 03:53
Currently looking to pull master, volume and filer logs, though they did not appear to report errors.

**Comment by ProjectInitiative** [comment] 2022-06-15 04:01
Testing with small text file yields expected behavior, larger files do not.
```bash
root:/mnt/swfs# cat test.txt 
this is a very important text file

root:/mnt/swfs# md5sum test.txt 
f473946c76d415891a380bb308a24086  test.txt

root:/mnt/swfs# cp test.txt localshared/
root:/mnt/swfs# cat localshared/test.txt 
this is a very important text file

root:/mnt/swfs# md5sum localshared/test.txt 
f473946c76d415891a380bb308a24086  localshared/test.txt

```

**Comment by chrislusf** [comment] 2022-06-15 04:52
how large is the large file?

**Comment by chrislusf** [comment] 2022-06-15 06:26
can not reproduce. can you start "weed mount" directly and show the output?

**Comment by ningfdx** [comment] 2022-06-15 07:06
can not reproduce too, Is the /sbin/weed version same as filer/master/volume's weed version? @ProjectInitiative 

![Screenshot from 2022-06-15 15-03-14](https://user-images.githubusercontent.com/17705801/173763779-39057bcc-06f9-4c7f-a0b8-972475c42de2.png)

**Comment by agipson33** [comment] 2022-06-15 14:26
I didn't include that detail, but I'm using 512GB volume files.

**Comment by ProjectInitiative** [comment] 2022-06-15 16:06
I am only having this problem with `.qcow2` `.raw` and `.vmdk` files (note these are not connected to any active VMs, just backup files. 

### file disk.raw
`DOS/MBR boot sector; partition 1 : ID=0xa5, active, start-CHS (0x0,1,2), end-CHS (0x3ff,255,63), startsector 64, 16777152 sectors`

### file disk.qcow2
`QEMU QCOW2 Image (v3), 8589934592 bytes`

### file disk.vmdk
`VMware4 disk image`

The checksums change on every run. ISO, tgz and other file formats are fine.

**Comment by ProjectInitiative** [comment] 2022-06-15 18:07
## More information

Running a CRC several times reports same number of bytes, but changing hashes.

```bash
root:~# cksum /mnt/swfs/localshared/disk.raw 
2184142024 8589934592 /mnt/swfs/localshared/disk.raw
root:~# cksum /mnt/swfs/localshared/disk.raw 
2208620223 8589934592 /mnt/swfs/localshared/disk.raw
root:~# cksum /mnt/swfs/localshared/disk.raw 
2558522723 8589934592 /mnt/swfs/localshared/disk.raw
```
Still very perplexing. No errors in logs still.

**Comment by chrislusf** [comment] 2022-06-15 18:16
can you show the output of `fs.meta.cat /localshared/disk.raw` in `weed shell`
and `cmp /mnt/swfs/localshared/disk.raw /var/lib/pve/local-btrfs/images/525/vm-525-disk-0/disk.raw`

**Comment by ProjectInitiative** [comment] 2022-06-15 18:41
## Multiple `cmp`
```bash
root:/mnt/swfs/localshared# cmp /var/lib/pve/local-btrfs/images/525/vm-525-disk-0/disk.raw /mnt/swfs/localshared/disk.raw 
/var/lib/pve/local-btrfs/images/525/vm-525-disk-0/disk.raw /mnt/swfs/localshared/disk.raw differ: byte 770049, line 120
root:/mnt/swfs/localshared# cmp /var/lib/pve/local-btrfs/images/525/vm-525-disk-0/disk.raw /mnt/swfs/localshared/disk.raw 
/var/lib/pve/local-btrfs/images/525/vm-525-disk-0/disk.raw /mnt/swfs/localshared/disk.raw differ: byte 1032193, line 120
root:/mnt/swfs/localshared# cmp /var/lib/pve/local-btrfs/images/525/vm-525-disk-0/disk.raw /mnt/swfs/localshared/disk.raw 
/var/lib/pve/local-btrfs/images/525/vm-525-disk-0/disk.raw /mnt/swfs/localshared/disk.raw differ: byte 655361, line 120
```
[weed.shell.fs.meta.cat.txt](https://github.com/chrislusf/seaweedfs/files/8912199/weed.shell.fs.meta.cat.txt)

**Comment by chrislusf** [comment] 2022-06-15 19:05
ok. Possible to share the `vm-525-disk-0/disk.raw` file also?

**Comment by ProjectInitiative** [comment] 2022-06-15 19:51
Can't share 525, but I can share a sanitized version 530. Same issue.

### local md5
```bash
root:~# md5sum /var/lib/pve/local-btrfs/images/530/vm-530-disk-0/disk.raw 
83d1eb4363be4f9dd7857127b270394a  /var/lib/pve/local-btrfs/images/530/vm-530-disk-0/disk.raw
```
[file on GDrive](https://drive.google.com/file/d/1Zc378BpqBFbeLAffzhmWJP0_pJKHIdY5/view?usp=sharing) was to big for GH

### weed md5
```bash
root:~# md5sum /mnt/swfs/localshared/disk-530.raw 
a980f8d99ef88101d749fcbda3191484  /mnt/swfs/localshared/disk-530.raw
root:~# md5sum /mnt/swfs/localshared/disk-530.raw 
6bf4b4c791630c9d5f913e44c643dd39  /mnt/swfs/localshared/disk-530.raw
```

### cmp

```bash
root:~# cmp /var/lib/pve/local-btrfs/images/530/vm-530-disk-0/disk.raw /mnt/swfs/localshared/disk-530.raw 
/var/lib/pve/local-btrfs/images/530/vm-530-disk-0/disk.raw /mnt/swfs/localshared/disk-530.raw differ: byte 114689, line 48
root:~# cmp /var/lib/pve/local-btrfs/images/530/vm-530-disk-0/disk.raw /mnt/swfs/localshared/disk-530.raw 
/var/lib/pve/local-btrfs/images/530/vm-530-disk-0/disk.raw /mnt/swfs/localshared/disk-530.raw differ: byte 770129, line 50
root:~# cmp /var/lib/pve/local-btrfs/images/530/vm-530-disk-0/disk.raw /mnt/swfs/localshared/disk-530.raw 
/var/lib/pve/local-btrfs/images/530/vm-530-disk-0/disk.raw /mnt/swfs/localshared/disk-530.raw differ: byte 56131585, line 2821
```

### weed shell fs.meta.cat
[weed.shell.fs.meta.cat.530.txt](https://github.com/chrislusf/seaweedfs/files/8912408/weed.shell.fs.meta.cat.530.txt)

**Comment by ProjectInitiative** [comment] 2022-06-17 03:55
@kmlebedev is that expected behavior? I assume one would be able to have multiple connections, and the masters/filers would handle two clients trying to write to the same volume.

**Comment by xdadrm** [comment] 2022-06-18 10:17
Just a thought.

I have experienced 'changing checksums' as well while running multiple filers, a vew versions back
It appeared to be filer's Metadata getting out of sync. Fixes are mentioned for metadata-sync in recent versions, but I haven't found the courage to try again [yet] :)

For me the issue went away when I switched to a single filer.
Might be worthwhile to switch to a single filer and check if checksums stabilize then.

**Comment by ProjectInitiative** [comment] 2022-06-18 16:41
@xdadrm I think that is the right path. Looks like my filers are out of sync. Going to try backing up and retrying. Not sure why or how they got out of sync.

**Comment by acejam** [comment] 2022-06-19 13:43
> @xdadrm I think that is the right path. Looks like my filers are out of sync. Going to try backing up and retrying. Not sure why or how they got out of sync.
> 
> That would explain why the problem was being very elusive and hard to reproduce.

I've done extensive testing of the leveldb filer stores and I've always had eventual consistency issues at higher request rates, caused by them getting out of sync. (In this case, they were backlogged due to high request rate)

The solution for me was to use a single filer store, MySQL in my case, and have multiple filer instances in front of it. With this configuration, all filer are stateless as they use a shared filer store.

**Comment by ProjectInitiative** [comment] 2022-06-20 21:04
Moved to a distributed filer store (TiDB) and the checksum issues have gone away. Still having issues where if two FUSE clients try to write to the same directory/file, things start getting inconsistent. Replicated local filer stores seem to be the cause of the original issue. I will close this for now. Will probably open another issue later regarding inconsistencies regarding concurrency. I believe NFS implements some locking mechanisms so multiple clients don't corrupt shared files (such as db and vm files on hci). Judging by the stateless nature of the filers, not sure this is possible in the current case (all speculation). Feel free to re-open.

**Comment by ProjectInitiative** [comment] 2022-06-21 00:41
Reopening as after further testing, even with a single, shared database, (TiDB) filers are reporting incorrect checksums again.

**Comment by ProjectInitiative** [comment] 2022-06-21 01:10
Doing more digging, I am not sure this is a filer issue. Looks to be more of a FUSE issue. Copying the files from the any of the filer web interfaces provides consistent results. Any data read from the FUSE mounts consistently provide inconstant results across the whole cluster.

**Comment by xdadrm** [comment] 2022-06-22 17:35
@ProjectInitiative 

could that be what you observe :

[Files copied to seaweed via webdav show as 0 size when accessed via fuse](https://github.com/chrislusf/seaweedfs/issues/3217)

**Comment by ProjectInitiative** [comment] 2022-06-23 12:16
@xdadrm unfortunately I have not quite run into that problem. I am able to upload data from WEBDAV, FUSE or filter web and data is fine. I can download from all of those methods too. Except the FUSE mount seems to be finicky when reading data.

**Comment by xdadrm** [comment] 2022-06-23 12:30
@ProjectInitiative thanks - that is interesting indeed. I too can upload and download via all three methods just fine.

Only when the files is copied in via WebDav  and the read vias Fuse it will show as 0 bytes, but is perfectly fine via other methods. Even reproduces easily on a fresh VM.
Ah well.

**Comment by ProjectInitiative** [comment] 2022-06-25 04:10
At a loss for how to provide any more info for a reproducible case. The issue still persists, I believe it has to do with multiple FUSE clients trying to access the same data, causing inconsistency. If there is a recommended way to provide atomic access to the same data (like NFS) I'm all ears.

**Comment by chrislusf** [comment] 2022-06-25 06:08
how to reproduce? seems more than just copying the file from one client.

**Comment by ProjectInitiative** [comment] 2022-08-03 01:43
@chrislusf hard to provide a reproducible example as this requires proxmox 7.2 to test. I have also been doing some testing with libvirt/qemu locally with a test install and experience similar behavior with VM disks not reading and writing correctly

**Comment by chrislusf** [comment] 2022-08-12 20:34
Does this problem still happen with 3.20? It has a fix which should help a bit.

I would like to have some integration test setup with qemu.

**Comment by ProjectInitiative** [comment] 2022-08-12 22:37
I tested with 3.20, still having issues.

I am trying to figure out an easy, repeatable test since the nature of the problem is complex. I was able to have similar issues with qemu, therefore I think a bash script might be possible . I'll update this thread if I find got something.

**Comment by chrislusf** [comment] 2022-08-30 08:25
Do you want to test the latest dev version? It has a fix for concurrent writes.

**Comment by chrislusf** [comment] 2022-08-30 08:27
Related to https://github.com/seaweedfs/seaweedfs/issues/3535

**Comment by ProjectInitiative** [comment] 2022-08-30 13:17
Tried testing, but the filer is returning 
`Aug 30 08:15:32 pve2 weed-filer[3135890]: I0830 08:15:32.715054 masterclient.go:223 .filer masterClient failed to receive from 127.0.0.1:9333: EOF`

**Comment by chrislusf** [comment] 2022-08-30 13:44
The fix was for "weed mount". 

The filer error logs seem about some wrong settings for master?

**Comment by ProjectInitiative** [comment] 2022-08-30 13:53
I should have clarified. The mount could not connect to the filer because of the above error when the filer is not starting. I haven't changed any settings. I can see if there is something going on with master settings.

**Comment by chrislusf** [comment] 2022-09-06 02:09
Closing this issue for now.

@ProjectInitiative could you please confirm the fix?

**Closed by chrislusf** 2022-09-06 02:09 UTC

**Comment by ProjectInitiative** [comment] 2022-09-06 15:24
checksums seem to work. qemu still reporting corruption happening. At this point not sure if it is related to the original issue, or a new issue. I will note that the new code was not compatible with my cluster, I needed to wipe clean and restore from a backup of the data. Volume servers and master servers would not start with the upgrade.
